const sampleData = {
  users: [
    {
      name: 'John',
      email: 'admin@example.com',
      password: '123456',
      role: 'admin',
    },
    {
      name: 'Jane',
      email: 'user@example.com',
      password: '123456',
      role: 'user',
    },
  ],
  products: [
    {
      name: '투데이라섹',
      slug: 'today-lasik',
      category: '시력 교정 수술',
      description: '근시, 난시 엑스머레이저 교정수술',
      images: ['/images/surgery/two-day-lasik-1.png'],
      price: 2800000,
      brand: '강남토스안과',
      rating: 4.5,
      numReviews: 12,
      stock: 9999,
      isFeatured: true,
      banner: '/images/surgery/two-day-lasik-1.png',
    },
    {
      name: '스마일라식',
      slug: 'smile-lasik',
      category: '시력 교정 수술',
      description: '근시, 난시 펨토레이저 교정수술',
      images: ['/images/surgery/smile-lasik-1.png'],
      price: 2500000,
      brand: '강남토스안과',
      rating: 4.4,
      numReviews: 9,
      stock: 9999,
      isFeatured: true,
      banner: '/images/surgery/smile-lasik-1.png',
    },
    {
      name: '안내렌즈삽입술',
      slug: 'icl-lens-insertion',
      category: '렌즈삽입술',
      description: '근시, 난시 안내렌즈삽입 교정수술',
      images: ['/images/surgery/icl-1.png'],
      price: 6000000,
      brand: '강남토스안과',
      rating: 4.8,
      numReviews: 20,
      stock: 9999,
      isFeatured: true,
      banner: '/images/surgery/icl-1.png',
    },
    {
      name: '크로스링킹',
      slug: 'cross-linking',
      category: '각막 치료 수술',
      description: '원추각막 치료 수술',
      images: ['/images/surgery/crosslinking-1.png'],
      price: 2500000,
      brand: '강남토스안과',
      rating: 4.1,
      numReviews: 6,
      stock: 9999,
      isFeatured: false,
      banner: '/images/surgery/crosslinking-1.png',
    },
    {
      name: '아이클린 리드클리너',
      slug: 'eye-clean-lid-cleaner',
      category: '눈꺼풀 세정제',
      description:
        '눈꺼풀과 속눈썹의 청결을 유지해주는 티트리 오일 성분의 세정제입니다.',
      images: ['/images/surgery/eye-clean-lid-cleaner.png'],
      price: 15000,
      brand: '바이오옵틱스',
      rating: 4.5,
      numReviews: 25,
      stock: 100,
      isFeatured: false,
      banner: null,
    },
    {
      name: '백내장 수술',
      slug: 'cataract-surgery',
      category: '백내장 수술',
      description: '일반 백내장 수술',
      images: ['/images/surgery/cataract-1.png'],
      price: 1350000,
      brand: '강남토스안과',
      rating: 4.3,
      numReviews: 10,
      stock: 9999,
      isFeatured: false,
      banner: '/images/surgery/cataract-1.png',
    },
    {
      name: '테크니스 퓨어씨',
      slug: 'technis-purec',
      category: '다초점 인공수정체',
      description: '원거리, 중간거리 생활형 근거리까지 선명한 인공수정체',
      images: ['/images/surgery/technis-pure-1.png'],
      price: 3000000,
      brand: 'Technis',
      rating: 4.6,
      numReviews: 15,
      stock: 9999,
      isFeatured: true,
      banner: '/images/surgery/technis-pure-1.png',
    },
    {
      name: '테크니스 멀티포컬',
      slug: 'technis-multifocal',
      category: '다초점 인공수정체',
      description:
        '원거리, 중간거리, 근거리 시력을 모두 교정하는 다초점 인공수정체',
      images: ['/images/surgery/technis-multifocal.png'],
      price: 3000000,
      brand: 'Technis',
      rating: 4.4,
      numReviews: 10,
      stock: 9999,
      isFeatured: false,
      banner: '/images/surgery/technis-multifocal.png',
    },
    {
      name: '파인비전',
      slug: 'finevision',
      category: '다초점 인공수정체',
      description:
        '원거리, 중간거리, 근거리 시력을 모두 교정하는 다초점 인공수정체',
      images: ['/images/surgery/finevision.png'],
      price: 3000000,
      brand: 'FineVision',
      rating: 4.3,
      numReviews: 9,
      stock: 9999,
      isFeatured: false,
      banner: '/images/surgery/finevision.png',
    },
    {
      name: '리사트리',
      slug: 'lisatry',
      category: '다초점 인공수정체',
      description:
        '원거리, 중간거리, 근거리 시력을 모두 교정하는 다초점 인공수정체',
      images: ['/images/surgery/lisatry.png'],
      price: 6000000,
      brand: 'LISA',
      rating: 4.6,
      numReviews: 7,
      stock: 9999,
      isFeatured: false,
      banner: '/images/surgery/lisatry.png',
    },
    {
      name: '테크니스 심포니',
      slug: 'technis-symphony',
      category: '연속초점 인공수정체',
      description:
        '원거리, 중간거리, 근거리 시력을 모두 교정하는 연속초점 인공수정체',
      images: ['/images/surgery/technis-symphony.png'],
      price: 3500000,
      brand: 'Technis',
      rating: 4.5,
      numReviews: 11,
      stock: 9999,
      isFeatured: false,
      banner: '/images/surgery/technis-symphony.png',
    },
    {
      name: '클라레온 팬옵틱스',
      slug: 'clareon-panoptix',
      category: '다초점 인공수정체',
      description:
        '원거리, 중간거리, 근거리 시력을 모두 교정하는 4중초점 인공수정체',
      images: ['/images/surgery/clareon-panoptix.png'],
      price: 4000000,
      brand: 'Clareon',
      rating: 4.6,
      numReviews: 14,
      stock: 9999,
      isFeatured: false,
      banner: '/images/surgery/clareon-panoptix.png',
    },
    {
      name: '인텐시티',
      slug: 'intensity',
      category: '다초점 인공수정체',
      description:
        '5중 초점을 적용하여 원거리, 중간거리, 근거리 시력을 모두 교정하는 다초점 인공수정체',
      images: ['/images/surgery/intensity.png'],
      price: 3000000,
      brand: 'Intensity',
      rating: 4.3,
      numReviews: 10,
      stock: 9999,
      isFeatured: false,
      banner: '/images/surgery/intensity.png',
    },
    {
      name: '비비티',
      slug: 'viviti',
      category: '다초점 인공수정체',
      description:
        '원거리, 중간거리, 근거리까지 확장된 시야를 제공하는 다초점 인공수정체',
      images: ['/images/surgery/vivity.png'],
      price: 4000000,
      brand: 'Vivity',
      rating: 4.4,
      numReviews: 13,
      stock: 9999,
      isFeatured: false,
      banner: '/images/surgery/vivity.png',
    },
    {
      name: '테크니스 시너지',
      slug: 'technis-synergy',
      category: '다초점 인공수정체',
      description: '연속초점과 다초점 인공수정체의 장점을 결합한 인공수정체',
      images: ['/images/surgery/technis-synergy.png'],
      price: 4000000,
      brand: 'Technis',
      rating: 4.5,
      numReviews: 12,
      stock: 9999,
      isFeatured: false,
      banner: '/images/surgery/technis-synergy.png',
    },
    {
      name: '아티스 심비오스',
      slug: 'artis-symbios',
      category: '연속초점 인공수정체',
      description:
        '연속초점 렌즈의 장점을 유지하며 근거리 시력을 강화한 인공수정체',
      images: ['/images/surgery/artis-symbios.png'],
      price: 4000000,
      brand: 'Artis',
      rating: 4.4,
      numReviews: 11,
      stock: 9999,
      isFeatured: false,
      banner: '/images/surgery/artis-symbios.png',
    },
  ],
};

export default sampleData;
